all:
	gcc -fopenmp -o clusterSearch clusterSearch.c -O3
	gcc -fopenmp -o preprocess preprocess.c -O3
	gcc -fopenmp -o linearSearch linearSearch.c -O3

clean:
	rm -f clusterSearch preprocess linearSearch

